name: Test
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
          - 4b1de714df305cbacbcf82bce58e963871c21f80 # master
          - 3559e11f753602a6272f682cc74dc95100dbcd81 # mine
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: jurplel/install-qt-action
          ref: ${{ matrix.repo }}

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: action/

      - run: |
          pushd action
          npm ci || npm install
          npm run build
          popd
          sed -i.bak 's|uses: $/action|uses: ./action|' action.yml
          diff -u action.yml.bak action.yml || true
          git status --porcelain

      - name: Install Qt Android
        uses: ./
        with:
          version: '<6.7'
          target: 'android'
          arch: 'android_arm64_v8a'
          dir: '${{ github.workspace }}/example/'
          install-deps: 'true'
          modules: 'qtcharts qtwebengine'
          archives: 'qtbase qtsvg'
          cache: 'true'
          cache-key-prefix: 'install-qt-action'
          setup-python: 'true'
          tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
          set-env: 'true'
          tools-only: 'false'
          aqtversion: '==3.3.*'
          py7zrversion: '==1.1.0'
          extra: '--external 7z'
          use-official: false
          email: ${{ secrets.QT_EMAIL }}
          pw: ${{ secrets.QT_PW }}

          aqtsource: git+https://github.com/miurahr/aqtinstall.git@076e1659807d0b362a3ed684d54c2e9c775eb9c7
