name: Test
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: pzhlkj6612/forked-install-qt-action
          ref: cac6ac70422104e1094ff308ed01f233bc8f0199

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: action/

      - run: |
          pushd action
          npm ci || npm install
          npm run build
          popd
          sed -i.bak 's|uses: $/action|uses: ./action|' action.yml
          diff -u action.yml.bak action.yml || true
          git status --porcelain

      - name: Install Qt Android
        uses: ./
        with:
          version: 6.11.1
          target: 'desktop'
          arch: 'linux_gcc_64'
          modules: qtwebview qtpositioning qtlocation qtpdf
          tools: 'tools_ifw'
          cache: true
          aqtsource: git+https://github.com/miurahr/aqtinstall.git@076e1659807d0b362a3ed684d54c2e9c775eb9c7
