name: Test
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Qt Android
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.11.1
          target: android
          arch: android_arm64_v8a
          modules: qtwebview qtpositioning qtlocation qtpdf
          cache: true
